#!/bin/bash
set -ex

echo; echo
echo "Wiring up to Cloud Foundry at ${CF_API}..."
echo
cf api "${CF_API}" --skip-ssl-validation
cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
cf target -o "${CF_ORG}" "${CF_SPACE}"

echo; echo
echo "Unmapping route from venerable app..."
cf unmap-route venerable-app apps.cfna2018.starkandwayne.com --hostname ${USERNAME}-app
cf apps

echo; echo
echo "DONE"
exit 0
