#!/bin/bash
set -ex

echo; echo
echo "Wiring up to Cloud Foundry at ${CF_API}..."
echo
cf api "${CF_API}" --skip-ssl-validation
cf auth "${CF_USERNAME}" "${CF_PASSWORD}"
cf target -o "${CF_ORG}" -s "${CF_SPACE}"

echo; echo
echo "Re-mapping routes to venerable app version..."
cf map-route venerable-app apps.cfna2018.starkandwayne.com --hostname ${USERNAME}-app

echo; echo
echo "Deleting candidate app..."
cf delete -f app
cf rename venerable-app app
cf apps

echo; echo
echo "DONE"
exit 0
